### PR TITLE
center <a> <href> tags html_functions.c

### PR DESCRIPTION
**Pull request by UnicornRiley**

### CODE REVIEW

**Comment by andy5995** [comment]
@UnicornRiley Thanks for the submission. Is there a reason you suggest this method over CSS?

**Comment by UnicornRiley** [comment]
Not sure, perhaps me not knowing CSS as much as I'd like

**Comment by UnicornRiley** [comment]
I apologize if it isn't what you was looking for, if you have any feed
back, please let me know. I know I am no-where near perfect with this stuff
and any feed back is very appreciated!

**Comment by andy5995** [comment]
No worries, @UnicornRiley . I appreciate the thought. Stop the chat room sometime and maybe we can figure out a good ticket for you. I like to teach, so I have no problem if people have questions and are interested in learning.

**Comment by UnicornRiley** [comment]
Sure if I can find it, no where near experienced at GitHub, just yesterday
I learned how to do pull-requests, so slowly learning, but GitHub seems
like an awesome place. Thank you a lot

**Comment by andy5995** [comment]
@UnicornRiley You're welcome. :) And welcome to GitHub! As for the Gitter chat room, you'll be able to find the link for that on https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
