### PR TITLE
[ Replaced text ] - replaced `.html` with `NULL`

### PR DESCRIPTION
**Pull request by moidmw**

### CODE REVIEW

**Comment by andy5995** [comment]
Thanks for doing @moidmw . Once you remove the "NUll" I can merge it in.

**Comment by andy5995** [comment]
We'll use the tags.txt file from #93 (ping #78)

**Comment by moidmw** [comment]
My bad.. have been out of town, so couldn't get a chance to fix it. Happy that it's already done. :+1:

**Comment by andy5995** [comment]
Ah, ok. If this situation arises again, I'll allow for more time. Thanks for following up with me. :)

**Pull request closed without merging**
