### PR TITLE
closed #32 (centered body text and relocated css)

### LINKED ISSUE #32: center the text on the web site
A lot of the CSS and html code is in

https://github.com/andy5995/mhwkb/blob/master/html_functions.c

It should be somewhat clear by looking at the other .c file how it's applied:

https://github.com/andy5995/mhwkb/blob/c16659583fee5a7647c22acc619eaa23a0b0872a/mhwkb_md2html.c#L163

It may be a bit confusing for those not familiar with C, but you'll see basically that the formatting is the same, just with a few extra chars. :)

Here's what the site looks like now: https://mhwkb.github.io/

We need some centering.. and probably some other ideas. If you like to play with html and css and have some ideas, please feel free to open some new tickets for separate ideas.

Please remember to "star" this project (upper right corner).

### PR DESCRIPTION
**Pull request by Krazete**

### CODE REVIEW

**Comment by andy5995** [comment]
Oh, thanks, @Krazete but I took care of the separation. It's best to mention on the ticket if you plan to work on something, in cases like this.

If you'd like to try again despite the inconvenience, I'd be grateful to accept another PR from you to help with the centering. If so, I'll take a look at it tomorrow. I'm done for the night.

**Comment by Krazete** [comment]
Sorry about that, I'm new to this pull request thing. Thanks for the advice.

**Comment by andy5995** [comment]
No worries. I remember when I was new too. I have some pretty good instructions on the CONTRIBUTING page. Basically, the procedure I show on there is the preferred method for doing PR's and syncing your repo on most all GitHub projects.

I wonder about putting a table in the middle of the page. Like 400px, and then left-aligning the text against the left-border of the table. You know what I mean? So it's still center, but the text is aligned from top to bottom. Do you have any opinion on how we could make that look nicer?

Also would be nice if those long titles wrapped inside the table. So... a margin of maybe 200px on the left and 200px on the right, and a table in the middle.

You should come hang out in the chat room; probably some more stuff coming up soon if you're interested.

**Comment by Krazete** [comment]
I realize now that I just blindly centered the body without paying attention to the rest of the format.
Yeah, I agree with your idea. But I think it'd require a change in the HTML (and maybe separate it from the C code as much as possible as well). I'll put up a new issue for that.

**Pull request merged**
